environment:
  BINSTAR_TOKEN:
    secure: +OdcMIEXLN/JkgaD3TxxMkfzQIAnPcnXSEg0mLcPIz7DADvjh20/dqLafoRNoaeA
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"
    PYTHONHASHSEED: "0"

  matrix:
    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - powershell .\\continuous-integration\\appveyor\\install.ps1  # installing miniconda for windows
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - conda config --set always_yes true
  - conda install conda conda-build anaconda anaconda-client requests jinja2 -y -q # this has to go into the root environment

  # Compile DLLs
  - cmd: IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" (sh .\\continuous-integration\\appveyor\\compile_htmdlib.sh)

  ### Creating an environment to install htmd deps and build
  - conda create -q -n travis-env python=%PYTHON_VERSION%
  - activate travis-env
  - conda config --add channels acellera
  # installing all deps
  - conda install --file package/htmd-deps/DEPENDENCIES_WIN -y
  - python package/htmd-deps/write_meta_yaml.py package/htmd-deps


build: false # Not a C# project, build stuff at the test step instead.

test_script:
  # run testsuite and upload test results to AppVeyor; return exit code of testsuite

  - set BUILD_VERSION=0.0.0
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (set BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%)

  - conda build --python %PYTHON_VERSION% package/htmd-deps --no-include-recipe
  - deactivate travis-env
  - python continuous-integration\move-conda-package.py

  - activate travis-env
  - conda build --python %PYTHON_VERSION% package/htmd --no-include-recipe
  - deactivate travis-env
  - python continuous-integration\move-conda-package.py

# artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  # - path: '*.tar.bz2'

on_success:
  # Upload built binaries to binstar.org. The globbing and handling of the
  # exit-status code is tricky in cmd.exe or powershell, so we're just using
  # a python script.
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (python continuous-integration\binstar-push.py)